name: Daily Price Tracker

on:
  schedule:
    # every day at 08:00 Italy time (06:00 UTC)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - uses: actions/checkout@v3

      # Install system dependencies for Matplotlib (headless)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1

      # Setup Chrome/Chromium for Selenium
      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager matplotlib

      # Run the script
      - name: Run price tracker script
        run: python both_adv_telegram.py

      # Upload artifacts (CSV and PNG)
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: price-tracking-data
          path: |
            price_history.csv
            price_history.png
          if-no-files-found: warn
