name: Daily Price Tracker

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager matplotlib

      - name: Run price tracker
        run: python both_adv_telegram.py

      - name: Upload artifacts (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: price-data
          path: |
            *.csv
            *.png
          if-no-files-found: ignore