name: Daily Price Tracker

# When to run the workflow
on:
  schedule:
    - cron: '0 6 * * *'  # every day at 08:00 Italy time (06:00 UTC)
  workflow_dispatch:     # allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install required libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager matplotlib

      # Run the price tracker script
      - name: Run price tracker
        run: python script.py