name: Daily Price Tracker

# Quando eseguire il workflow
on:
  schedule:
    - cron: '0 8 * * *'  # ogni giorno alle 08:00 UTC
  workflow_dispatch:     # permette di eseguire manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Clona la repo
      - uses: actions/checkout@v3

      # Imposta Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installa le librerie necessarie
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager matplotlib

      # Esegui lo script
      - name: Run price tracker
        run: python script.py
