name: Daily Price Tracker

# When to run the workflow
on:
  schedule:
    - cron: '0 6 * * *'  # every day at 08:00 Italy time (06:00 UTC)
  workflow_dispatch:     # allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    # IMPORTANT: Permissions to commit to the repository
    permissions:
      contents: write

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install required libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager matplotlib

      # Run the price tracker script
      - name: Run price tracker
        run: python script.py

      # NEW: Automatically commit generated files
      - name: Commit and push price data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Daily price update"
          file_pattern: "price_history.csv price_history.png"
          commit_user_name: "Price Tracker Bot"
          commit_user_email: "actions@github.com"
